from tkinter import *
root=Tk()
root.title("Note pad")
root.geometry('500x500')

def fun1():
    print(exit())

menu1=Menu(root)
root.config(menu=menu1)
submenu=Menu(menu1)
menu1.add_cascade(label="File", menu=submenu)
submenu.add_command(label="New")
submenu.add_command(label="New Window ")
submenu.add_command(label="Open...")
submenu.add_separator()
submenu.add_command(label="Save")
submenu.add_command(label="Save as ")
submenu.add_command(label="Page Setup")
submenu.add_command(label="Print ")
submenu.add_separator()
submenu.add_command(label="Exit      ",command=fun1)
menu2=Menu(menu1)
menu1.add_cascade(label="Edit", menu=menu2)
menu2.add_command(label="Cut" )
menu2.add_command(label="Copy" )
menu2.add_command(label="Delete" )
menu2.add_command(label="Paste" )
menu2.add_separator()
menu2.add_command(label="Find" )
menu2.add_command(label="Find Next" )
menu2.add_command(label="Find Previous" )
menu2.add_separator()
menu2.add_command(label="Replace" )
menu2.add_command(label="Go To" )
menu2.add_command(label="Select All" )
menu2.add_command(label="Time/Date" )
menu3=Menu(menu1)
menu1.add_cascade(label="Format", menu=menu3)
menu3.add_command(label="   Word Wrap  ")
menu3.add_command(label="   Font..  ")
menu4=Menu(menu1)
menu1.add_cascade(label="View", menu=menu4)
menu4.add_command(label="  Zoom  ")
menu4.add_command(label="  Status Bar  ")
menu5=Menu(menu1)
menu1.add_cascade(label="Help", menu=menu5)
menu5.add_command(label="View Help")
menu5.add_command(label="Send Feedback")
menu5.add_separator()
menu5.add_command(label="About NotePad")


root.mainloop()
